### ISSUE TITLE
Password Hash Cache not working as expected

### ISSUE THREAD

**Issue by booherbg** [jwag956/flask-security#124]
Hi there. I seem to be in the minority, but the password caching mechanism does not work out of the box for me (#91 seems to imply that it will work for some folks). I'm just using flask's built in dev server `flask run`

The main issue seems to be obvious: The cache is being stored in a werkzeug Local(), which (for me) gets wiped after every request. Thus the cache is working, in a sense, but it gets cleared after every request. This feels correct because the Locals() interface acts as a guard between accidentally sharing data across threads, where what I want is actually a shared cache between all threads. I want *all* my requests to be fast (and share their cache between all requests).

I fixed this by simply replacing the Locals() call with a globally instantiated call to the TTLCache (see below). I'll probably end up throwing this into Redis (so that I can share caches across like 20 workers). 

I've found the password verification to be a substantial bottleneck in my app where polling requests take at a minimum 700ms just to verify the hash (ugh) on every single auth-token request, which really starts to bog everything down if you're trying to stack requests or poll relatively quickly (like every couple seconds). If you've got a handful of requests across a handful of clients, forget about it. Thus I'm very interested in this feature, and a clean implementation that works for me.

So... am I doing something different from everyone else or do I have different requirements?

Before:
``` python
local_cache = Local()

# ...
def _request_loader(request):
    # ...
    use_cache = cv("USE_VERIFY_PASSWORD_CACHE")

    if not user:
        return _security.login_manager.anonymous_user()
    if use_cache:
        cache = getattr(local_cache, "verify_hash_cache", None)
        if cache is None: # its ALWAYS None!
            cache = VerifyHashCache()
            local_cache.verify_hash_cache = cache
        if cache.has_verify_hash_cache(user):
            return user
        if verify_hash(data[1], user.password):
            cache.set_cache(user)
            return user
    else:
        if verify_hash(data[1], user.password):
            return user
```
After:
``` python
#local_cache = Local()
verifyCache = None

# ...
def _request_loader(request):
   # ...

    use_cache = cv("USE_VERIFY_PASSWORD_CACHE")

    if not user:
        return _security.login_manager.anonymous_user()
    if use_cache:
        global verifyCache
        if (verifyCache is None):
            verifyCache = VerifyHashCache()
        if verifyCache.has_verify_hash_cache(user):
            return user
        if verify_hash(data[1], user.password):
            verifyCache.set_cache(user)
            return user
    else:
        if verify_hash(data[1], user.password):
            return user

    return _security.login_manager.anonymous_user()
```

Interestingly, this only partially fails on my production setup with gunicorn. But it only works if I refresh the page (and thus do couple of requests back to back). I assume that this is because gunicorn will maybe re-use the thread for requests from the same client within a window (or maybe Chrome is pipelining the http requests over a single socket).  However, if I just let it poll every few seconds it consistently misses the cache (presumably because gunicorn is resetting the thread).

I'm curious what setup everyone else is using where this "just works" for them?

**Comment by jwag956** [comment]
Thanks for the writeup - this is a new feature and flask-security-too is  new fork - so there aren't many people using this.

cachetools:LRUCache isn't thread-safe:
https://cachetools.readthedocs.io/en/latest/

so making it global probably isn't a good idea.

My reading of Werkzueg.Local is that it is per-thread - but not per-request. So if you have a standard uWsgi app with multiple processes and multiple threads - you will have a cache per - so yes - if a second request goes to a second thread - the first time, it will again compute the token-validity - but then cache. Not idea - but still better than every time. Depending on TTL - it should amortize out.

Related to your other comments (on the release) - if you are building a browser-based web site - then I think what you really want (and is fast) is to simply use sessions/cookies and stop using tokens altogether. I too started my carefully managing tokens in my SPA - but sessions are easier and MUCH more secure (and don't have the slow token authentication issue at all). I ripped out all my token code from the UI!

**Comment by booherbg** [comment]
@jwag956

So far I have not seen any issues with threading, in fact if anything I WANT the cache to be shared between threads :P

What I ended up doing was creating a fork, and then implementing a redid cache. That actually has worked perfectly for my use. It's really fast, an instantly available to all 20 of my workers. I can even put a relatively low TTL, so it gets refreshed more often.

I'm curious about how you did your sessions. Do you just grab the cross site request token one time, and just use that? That's been my largest hurdle. Once I found out that authentication tokens don't need the card token, that has been what I have been using.

Can you easily use a session with fetch()?

**Comment by jwag956** [comment]
what I meant by not-thread-safe is that if 2 threads attempt to add or delete elements at the same time - I believe the cache can get corrupted.

I don't personally use the cache (since it is new) and I use sessions. I merged it is since it seemed like a useful first step. In general, the underlying problem is how tokens were created and their desire to invalidate a token if the password changes. There are better ways to do that - and furthermore - most applications these days use things like oauth2 code grant for websites and client credentials for API access. That is on my TODO list but is relatively complex.

If you have time - I would be very interested in a PR that allowed for different cache plugins.

As for CSRF - well - I just disabled that :-( But since others are having similar issues I am working on how to support single-page-applications and CSRF and will get that ready in the next week or so.

**Comment by jwag956** [comment]
@booherbg I have been working on making FS more CSRF friendly (it really didn't work with API/json calls). I am curious by your stmt: "Once I found out that authentication tokens don't need the card token, " - how one authenticates shouldn't have anything to do with whether CSRF is enforced or not. That is dependent on a) WTF_CSRF_ENABLED=True (which is the default) and b) having a form that is derived from flask_wtf::FLaskForm (which all flask-security forms are).
Can you clarify how you are gettin around CSRF? (When I started, I simple set WTF_CSRF_ENABLED=False in my config....

**Comment by booherbg** [comment]
I can work on a cache plugin. I think that we should quantify what "thread safe" means in this context. It is acceptable for two threads to access the same item, but not acceptable if there is unexpected behaviour. In python at least I do not believe that the data structure would get corrupted, but I would like to verify.

As far as CSRF, you bring up a good point. Let me collect my thoughts and come back. I found that using the auth token skipped the csrf requirements for things like registration, but now in hindsight I'm not sure what the final impact is or which endpoints even require it.

**Comment by jwag956** [comment]
Thanks for getting back. First - I have a WIP for overhauling CSRF support - almost done and I think that should solve/make easy lots of issues folks have had.

Second - the more I think about caching - I think this is the wrong approach. I merged in the cache PR as a stop-gap measure. The only reason it is slow is that it is attempting to cause the token to become inactive if the user changes their password. I haven't researched why they did that - but I think that is the complete wrong direction. Tokens are for APIs used by scripts and other service to service operations. They should have nothing to do with a users password.
Right now, I believe that there is no way to disable a token (even marking a user as 'inactive' doesn't do it if I am reading code directly.

API tokens should be independent from username/password and should be revokable. This is how oauth2 works w.r.t. client credentials. I believe this is a much more scalable and secure model.
I have been looking at incorporating oauth2 provider (at least the client credential part) - and completely remove the current authtoken implementation

Since this is such a big issue - there are some stop-gaps that would be quick and easy - one would be to stop checking password match on each request. That would make the token work as long as its TTL. If we fix the 'inactive' to mean no longer access system - that might be enough for a start.

thoughts?

**Comment by jwag956** [comment]
We now have robust and fast token generation/validation in the system (via the new user field fs_uniquifier). The current cache will be removed in 4.0.

Also - marking a user as inactive now ensures that no token or session will be authenticated.
