### ISSUE TITLE
Logged in users accessing /login aren't redirected

### ISSUE THREAD

**Issue by kuba-lilz** [jwag956/flask-security#221]
My understanding is that when a logged in user accesses `/login` endpoint, she should be redirected to `SECURITY_POST_LOGIN_VIEW`.

It seems that with `flask-security-too==3.3.0` this behavior is broken - users aren't redirected, they are shown login form instead. Even stranger, after successful POST they still don't get redirected (while unauthenticated users that do successful POST login are redirected to `SECURITY_POST_LOGIN_VIEW`)

I confirmed this behavior with  `flask-security-too==3.3.0` and `flask-security-too==3.3.1`.
A also confirmed things work as expected with `flask-security-too==3.2.0` and master branch of original `flask-security`.

Here's a log of requests when logged in user accesses login endpoint:

### For  `flask-security-too==3.2.0`
```
14:45:03 flask.1   | 127.0.0.1 - - [28/Nov/2019 14:45:03] "GET /myapp/login HTTP/1.1" 302 -
14:45:03 flask.1   | 127.0.0.1 - - [28/Nov/2019 14:45:03] "GET /myapp HTTP/1.1" 308 -
14:45:03 flask.1   | 127.0.0.1 - - [28/Nov/2019 14:45:03] "GET /myapp/ HTTP/1.1" 200 -
```

### For `flask-security-too==3.3.0` and `flask-security-too==3.3.1`
```
14:47:55 flask.1   | 127.0.0.1 - - [28/Nov/2019 14:47:55] "GET /myapp/login HTTP/1.1" 200 -
14:48:00 flask.1   | 127.0.0.1 - - [28/Nov/2019 14:48:00] "POST /myapp/login HTTP/1.1" 200 -
```
(note that in second case I manually logged in/sent POST request after GET /login response and wasn't redirected).

Just for completeness - when unauthenticated user accesses `/login` view flow works as expected:
```
14:56:46 flask.1   | 127.0.0.1 - - [28/Nov/2019 14:56:46] "GET /myapp/login HTTP/1.1" 200 -
14:56:50 flask.1   | 127.0.0.1 - - [28/Nov/2019 14:56:50] "POST /myapp/login HTTP/1.1" 302 -
14:56:50 flask.1   | 127.0.0.1 - - [28/Nov/2019 14:56:50] "GET /myapp HTTP/1.1" 308 -
14:56:50 flask.1   | 127.0.0.1 - - [28/Nov/2019 14:56:50] "GET /myapp/ HTTP/1.1" 200 -
```

Also if logged in users accesses `/login` page and then manually goes to main page, she can access it without problems, no surprises here. 

Am I missing something some setting or is it really a bug? I know there were some big changes with `3.3.0` version, but I studied change log carefully and didn't see anything that would seem connected.

**Comment by jwag956** [comment]
Thanks for the detailed report.
I am AFK for a few days will look into it when I get back 
Seems like a bug

**Comment by jwag956** [comment]
Ok - this is due to the change to allow calls to /login when already authenticated.
In prior releases. the /login endpoint was decorated with @anonymous_user_required - which meant that if a logged in user did a GET or POST on /login - it would always trigger a:
return redirect(utils.get_url(_security.post_login_view)).

When the code was changed to 'handle' authenticated users as part of the /login view - those 2 cases were missed.
The fix is easy - however there is some uncertainty due to the 2 different mechanisms that historic FS uses to compute urls. The one above - get_url() basically just calls flask::url_for(). Most of the FS views that redirect for post_login, post_logout, post_register use a very different  set of routines that take into account ?next=xxx.

When fixing this - I am opting for using the routines that take into account ?next=xxx - which is a slight behavior change from older releases.

**As for the second issue** - doing a POST when already logged in - I can't reproduce that - it is true that it will log you out and back in again - but I get redirected to the post_login_view. Can you provide some details payloads?

**Comment by kuba-lilz** [comment]
> Ok - this is due to the change to allow calls to /login when already authenticated.

Roger that, thank you for confirming :)

> As for the second issue - doing a POST when already logged in - I can't reproduce that - it is true that it will log you out and back in again - but I get redirected to the post_login_view. Can you provide some details payloads?

This issue persists on my side :(
By saying payloads you mean request body/content of POST form?
Here are request contents for a few requests for user that first accesses `/login` unauthenticated, then authenticated. Since these endpoints live inside flask-security I got a hold of requests contents by adding `before_request` handler in my code. If you would like me to add some debug code directly to a specific flask-security view, I can do that as well.

```
# GET /login with unauthenticated user
request url is GET http://0.0.0.0:5000/login
request args are ImmutableMultiDict([])
request form data is ImmutableMultiDict([])
request session cookie is: {'session': '.eJwVjkFqQzEMBe_idReWLVl2LvORnyQoLQ0k2YXeve72zRuYd7k-vdwK53Su0oRAfS9DnW4THlyDs_EyP4w5lNbWiLHHAhvlprGMVBUV0M7LpVo3w6S5ZcWevdk5WNTe9IyQWkEJdfcUg3QfdZSPgucjr9f9K35ODza5Rzas7BLizRIDa6juyZKINk-k8PHyeQH_ynfYo_z-AV4QPGw.XeRqow.hKmCO46DDCy2R9O_cHKE-GI_yv4'}
127.0.0.1 - - [02/Dec/2019 10:36:39] "GET /login HTTP/1.1" 200 -

# POST /login with unauthenticated user
request url is POST http://0.0.0.0:5000/login
request args are ImmutableMultiDict([])
request form data is ImmutableMultiDict([('csrf_token', 'ImNiMWRkZWYyYzlmMzVlNWQyYWZjNmM5Njc3Yjg0NWZjZTI4OWFjNTQi.XeRqpw.bgBgN2aexTdQuhaLffDubU8HyMQ'), ('password', 'secret'), ('next', ''), ('email', 'testuser_01@myapp.com'), ('submit', 'ログイン')])
request session cookie is: {'session': '.eJwVjkFqQzEMBe_idReWLVl2LvORnyQoLQ0k2YXeve72zRuYd7k-vdwK53Su0oRAfS9DnW4THlyDs_EyP4w5lNbWiLHHAhvlprGMVBUV0M7LpVo3w6S5ZcWevdk5WNTe9IyQWkEJdfcUg3QfdZSPgucjr9f9K35ODza5Rzas7BLizRIDa6juyZKINk-k8PHyeQH_ynfYo_z-AV4QPGw.XeRqow.hKmCO46DDCy2R9O_cHKE-GI_yv4'}
127.0.0.1 - - [02/Dec/2019 10:37:04] "POST /login HTTP/1.1" 302 -

# Redirect after a successful login received
request url is GET http://0.0.0.0:5000/
request args are ImmutableMultiDict([])
request form data is ImmutableMultiDict([])
request session cookie is: {'session': '.eJwlj0tqBDEMRO_i9TTItmTZc5lG1oeEQALtnlWYu8eQZX0eVP2mMy5fH-l5Xy9_pPPT0jNhdEOgQllznUMUuklXcwTHKDjEdobonMdk9zbbUJQcM7chmZkVVLniMAKpItpznzR89lpkF8ShFt6mEoDmUDazIFGq1qClR9J1xXn_fPn33qMzm3kUHVHJyYqENh2NeXakUC99jyTcXKxTdSPL761ey6__S8yVSw48InQcWMOPidAOid5KxwhulN5_rJFNyw.XeRqwA.Q6PkwkO9u_-jjT2d-RjnwNpOgBg'}
127.0.0.1 - - [02/Dec/2019 10:37:04] "GET / HTTP/1.1" 200 -

# GET /login with authenticated user
request url is GET http://0.0.0.0:5000/login
request args are ImmutableMultiDict([])
request form data is ImmutableMultiDict([])
request session cookie is: {'session': '.eJwlj0tqBDEMRO_i9TTItmTZc5lG1oeEQALtnlWYu8eQZX0eVP2mMy5fH-l5Xy9_pPPT0jNhdEOgQllznUMUuklXcwTHKDjEdobonMdk9zbbUJQcM7chmZkVVLniMAKpItpznzR89lpkF8ShFt6mEoDmUDazIFGq1qClR9J1xXn_fPn33qMzm3kUHVHJyYqENh2NeXakUC99jyTcXKxTdSPL761ey6__S8yVSw48InQcWMOPidAOid5KxwhulN5_rJFNyw.XeRqwA.Q6PkwkO9u_-jjT2d-RjnwNpOgBg'}
127.0.0.1 - - [02/Dec/2019 10:38:21] "GET /login HTTP/1.1" 200 -

# POST /login with authenticated user
New request received
request url is POST http://0.0.0.0:5000/login
request args are ImmutableMultiDict([])
request form data is ImmutableMultiDict([('csrf_token', 'ImNiMWRkZWYyYzlmMzVlNWQyYWZjNmM5Njc3Yjg0NWZjZTI4OWFjNTQi.XeRrDQ.Gbb6U4q9pWf1ZQFxNHwtp-Y-K5Y'), ('password', 'secret'), ('next', ''), ('email', 'testuser_01@lilz.jp'), ('submit', 'ログイン')])
request session cookie is: {'session': '.eJwlj0tqBDEMRO_i9TTItmTZc5lG1oeEQALtnlWYu8eQZX0eVP2mMy5fH-l5Xy9_pPPT0jNhdEOgQllznUMUuklXcwTHKDjEdobonMdk9zbbUJQcM7chmZkVVLniMAKpItpznzR89lpkF8ShFt6mEoDmUDazIFGq1qClR9J1xXn_fPn33qMzm3kUHVHJyYqENh2NeXakUC99jyTcXKxTdSPL761ey6__S8yVSw48InQcWMOPidAOid5KxwhulN5_rJFNyw.XeRqwA.Q6PkwkO9u_-jjT2d-RjnwNpOgBg'}
127.0.0.1 - - [02/Dec/2019 10:38:44] "POST /login HTTP/1.1" 200 
# (notice no 302 redirect)
```

**Comment by kuba-lilz** [comment]
Some thoughts:
- `session` cookie didn't change between two POST requests. If I manually logout and log in again, session cookie changes. So that makes me think that user wasn't logged out and then back in on second `POST /login`
- On failed login `flask security` returns `200` response and shows reason logging failed in template with `render_field_with_errors`. Maybe my second `POST /login` did in fact fail, but there is no field on template that contains the error?

**Comment by kuba-lilz** [comment]
So continuing with second thought I tried adding 
```
print("Errors are:")
print(form.errors)
```
inside flask-security's `login` view (around views.py::210, so after `if form.validate_on_submit() condition` and lo and behold, for second `POST /login` request only I get:
```
Errors are:
{'csrf_token': ['The CSRF session token is missing.']}
```
Rather surprising, since logs above show we are including CSRF token.

I manually checked `csrf-token` in `GET /login` html for unauthenticated and authenticated cases and compared to what's sent in request body but there were no problems there - both POST requests sent `csrf-token` equal to what was in their respective `GET /login` forms.

And turns out I get logged out after that failed `POST` for logged-in user - trying to go to main page manually returns me back to login page. Strange, that wasn't behavior I saw before, unless my memory is playing tricks on me.

Also, after failed login of logged in user, if I try to login again, it works after 2nd time...
Here's the summary of responses and errors:

- `POST /login` after logging -> fails with `{'csrf_token': ['The CSRF session token is missing.']}` (though token is present in request body)
- `POST /login` again -> fails with `{'csrf_token': ['The CSRF tokens do not match.']}`
- `POST /login` again -> succeeds

**Comment by malware-watch** [comment]
I had a similar problem combined with Application Factories.
After initializing CSRFProtect it worked:

```
__init__.py
```

```python
csrf = CSRFProtect()
[..]
def create_app(): 
    [..]
    csrf.init_app(app)
```

**Comment by jwag956** [comment]
Ok - this all actually makes sense.

When doing a POST with an already authenticated user - the code logs out the current user. The goal was to allow a one-step login even if already logged in.

Part of logging out a user is to clear the CSRF token in the session. So then you get the first error:
"CSRF Session token is missing".  As with all POST errors - it simply returns a 200 with error filled in - but as you observed - the csrf_token is hidden so errors about it aren't shown.

You do it again - now you have a NEW session csrf token - but  you passed in (I believe) the original CSRF token - which of course - because of the new session csrf token - doesn't match.

Finally (I am surmising here) you are actually passing in a NEW csrf_token that was returned as part of the last error - and that then matches.

Whew.

As I ponder this more - I think the whole idea of allowing an already logged in user to POST /login again is flawed. First - if logging someone else in - that would mean using the same session cookie - which would never work with CSRF. 

So I think the best approach is to revert to prior behavior in the POST case - redirect to POST_LOGIN_VIEW (unless json).
The only odd thing about the old behavior is that if you POST with a form with a new user/email - you will get a 200 redirect to POST_LOGIN - but still be logged in as the 'old'/current user.

**Comment by kuba-lilz** [comment]
Glad to hear you the reason for observed behavior is understood.

I suppose it's a bit of design decision to answer whether that's a bug or a feature ^^
I'll leave the issue open, but please feel free to close it if this behavior isn't likely to change soon.

**Comment by jwag956** [comment]
It would be awesome if you had a chance to use the current master branch in your app/testing - it should have both the login redirect and 2FA fixes in. If that allows you to remove all your hacks and no more strange behavior - I will put out a 3.3.2 release onto pypi.
In any case I will probably push 3.3.2 out in the next few days.

Thanks for all your help.

**Comment by kuba-lilz** [comment]
I checked behavior for login redirection and required 2FA with latest master (`647ff48`) and they both behave as expected :) Thank you very much, it's really nice to see these in `flask-security`.

I have a small issue regarding `current_user.tf_primary_method` inconsistency between 2FA enabled and 2FA required, but that's best discussed separately #226
