### ISSUE TITLE
Add ability to use different login methods

### ISSUE THREAD

**Issue by LaundroMat** [jwag956/flask-security#65]
First of all, awesome of you @jwag956 to take this library into your hands! I hope I'll be able to contribute meaningfully to it.

I'm using passwordless login in one of my projects, but I've been having issues with email deliverability. I'd like to be able to add username/password login too, but currently there's only one method allowed per app (based on the config settings). So the ability to set multiple login methods would be helpful in my case.

I understand this suggestion might be a difficult one to implement, so please don't see this as an "I need this asap"-thing. I just wanted to log it here because I'm probably not the only one with this suggestion and open up the discussion.

**Comment by jwag956** [comment]
I think this is actually pretty easy - it just needs a new entry point since today /login is used for both. Some annoying backwards compat issues - but relatively easy.
I have a question for you  since you are using passwordless. Today, the token can have a TTL - but other than that, it can be used until expired. Is that your use case or is there reason to consider how to make these 'one-time' tokens. The same issue with reset-password token - until it expires, you can use it - which I don't think is quite correct.
Interested in your thoughts.

**Comment by LaundroMat** [comment]
Are you concerned about the security aspects of passwordless login? 

In any case, I am satisfied with how it works now. I haven't seen any misuse or heard feedback from users that they were experiencing problems.

In fact, I like it much better than social login or the classic login/password combo. It feels close to 2FA the way it works.

I'll look into a PR for this, but (like #77) it'll take a while. I've been having some hectic weeks and it's not over yet 😅

**Comment by jwag956** [comment]
I am not really worried (but see below). I am interested in your use case and how you configure it. In particular, as I mentioned - flask-security currently has a 'use until expired' model for its tokens.
I was wondering if that is what you like/dislike and what you set the TTL to. 

Best practice says not to send authentication tokens as query params. The rationale is that URLs, including query params are often logged - and logging anything secret is bad (and people don't necessarily take care of their logs very well and often lots of of people might have access to logs that shouldn't have access to users credentials). Oauth2 doesn't do this - sending a temporary token that is exchanged for the real one.
The current passwordless scheme (and reset password) isn't clear on this - it isn't one time so depending on your  TTL - it might be valid for a while and therefore a small security issue.
I am not certain that is a big risk for most flask-security folks - but is why I am interested in your use case.

**Comment by LaundroMat** [comment]
I'm using the default configuration: tokens do not expire and the link is never invalidated. It's not invalidated:
*  when I request another login link (meaning I can still log in using an "old" link)
*  when I log in using a newer link and then log out, I can still log in with the older link.

I understand the security risks better now, thanks. 

The two use cases I'm using it for are:
*  A tool to view and update contents of a DB. I need the login primarily to be able to log who has changed something and to provide more personalised views (i.e. only the stuff the logged in user "owns"). There's no problem if someone can see what other users "own" in the DB, so security is not a high priority.
*  A tool to build Kano surveys and analyses with. Here, security is more sensitive. People wouldn't want other people to be able to access their survey data and analyses.

Especially for the latter use case, invalidating tokens:
*  after a certain TTL
*  and/or after they have been used
*  and/or after a new token has been issued for the same user

would definitely be an improvement.

**Comment by jwag956** [comment]
Some additional thoughts.

passwordless login is definitely a growing 'thing'.
In general, TTLs are set low so that the 'replay'/reuse issue is small (i.e. O(minutes) as opposed to 1 day which is the default for FS).

Note: current passwordless token just represents the user.id - which isn't strictly unique since some DBs will re-use primary keys - so that is a (small) security issue that should be cleaned up.

My inclination would be to set the default TTL down to say 5 minutes (always configurable) since the current 1-day definitely has some replay attack issues (and user can always ask for another link).
Actually providing a OTP (one time password) would require additional DB field that records if a token was used or not. This has some advantages - but still - if a hacker got there first they could lock out the real intended user - but better especially for email-delivered reset tokens.

**Comment by jwag956** [comment]
#257 is I think the answer...
